FROM oven/bun:1
WORKDIR /app

COPY frontend/package.json frontend/bun.lockb ./
RUN bun install --production

COPY frontend/ .

RUN bun build src/server.ts --outdir dist

ENV NODE_ENV=production

EXPOSE 3000
CMD ["bun", "dist/server.js"]